AGENT_FQN = "INSURANCE_AI_HUB.ANALYTICS.INSURANCE_HUB_ORCHESTRATOR"

COLORS = {
    "blue": "#2196F3",
    "green": "#4CAF50",
    "orange": "#FF9800",
    "red": "#F44336",
    "purple": "#9C27B0",
    "grey": "#9E9E9E",
}

CHAT_SUGGESTIONS = [
    {"label": "Recommend the best products for high-value customers", "category": "matching"},
    {"label": "Which products have the highest acceptance rate?", "category": "matching"},
    {"label": "How do our prices compare to market benchmarks?", "category": "pricing"},
    {"label": "What are the top friction points causing delays?", "category": "pricing"},
    {"label": "Which accounts have the highest churn probability?", "category": "market"},
    {"label": "Show revenue at risk by category as a chart", "category": "market"},
    {"label": "Why did the data quality score drop recently?", "category": "dq"},
    {"label": "Which columns have the worst health scores?", "category": "dq"},
    {"label": "Search for specific terms in the knowledge base", "category": "docs"},
]

SQL_PREMIUM_VS_BENCHMARK = """
SELECT p.POLICY_TYPE, p.PLAN_TIER,
    ROUND(AVG(p.PREMIUM_AMOUNT), 2) AS OUR_AVG_PREMIUM,
    ROUND(AVG(cr.BENCHMARK_PREMIUM), 2) AS MARKET_AVG_PREMIUM,
    ROUND(AVG(p.PREMIUM_AMOUNT) - AVG(cr.BENCHMARK_PREMIUM), 2) AS PRICE_GAP
FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES p
JOIN INSURANCE_AI_HUB.ANALYTICS.COMPETITOR_RATES cr
    ON p.POLICY_TYPE = cr.POLICY_TYPE AND p.PLAN_TIER = cr.PLAN_TIER
WHERE cr.COMPETITOR_NAME = 'Market Average'
GROUP BY p.POLICY_TYPE, p.PLAN_TIER ORDER BY 1, 2"""

SQL_LOSS_RATIO_BY_TYPE = """
SELECT POLICY_TYPE, PLAN_TIER, ROUND(AVG(LOSS_RATIO), 3) AS AVG_LOSS_RATIO, COUNT(*) AS POLICY_COUNT
FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES WHERE POLICY_STATUS = 'Active'
GROUP BY POLICY_TYPE, PLAN_TIER ORDER BY AVG_LOSS_RATIO DESC"""

SQL_BILLING_SUMMARY = """
SELECT PAYMENT_STATUS, COUNT(*) AS INVOICE_COUNT,
    ROUND(SUM(OUTSTANDING_BALANCE), 2) AS TOTAL_OUTSTANDING,
    ROUND(SUM(LATE_FEE), 2) AS TOTAL_LATE_FEES
FROM INSURANCE_AI_HUB.ANALYTICS.BILLING GROUP BY PAYMENT_STATUS ORDER BY TOTAL_OUTSTANDING DESC"""

SQL_FRICTION_POINTS = """
SELECT FRICTION_POINT, COUNT(*) AS CLAIM_COUNT,
    ROUND(AVG(DAYS_TO_RESOLVE), 1) AS AVG_DAYS_TO_RESOLVE,
    ROUND(AVG(CLAIM_AMOUNT), 2) AS AVG_CLAIM_AMOUNT
FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE FRICTION_POINT IS NOT NULL
GROUP BY FRICTION_POINT ORDER BY CLAIM_COUNT DESC"""

SQL_MARKET_TRENDS = """
SELECT METRIC_NAME, METRIC_CATEGORY, REGION, PERIOD_DATE, METRIC_VALUE, CHANGE_PCT, TREND_DIRECTION
FROM INSURANCE_AI_HUB.ANALYTICS.MARKET_TRENDS ORDER BY METRIC_NAME, REGION, PERIOD_DATE"""

SQL_AT_RISK_SUMMARY = """
SELECT RISK_CATEGORY, COUNT(*) AS POLICY_COUNT,
    ROUND(SUM(REVENUE_AT_RISK), 2) AS TOTAL_REVENUE_AT_RISK,
    ROUND(AVG(CHURN_PROBABILITY), 3) AS AVG_CHURN_PROB,
    ROUND(AVG(RISK_SCORE), 2) AS AVG_RISK_SCORE
FROM INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES GROUP BY RISK_CATEGORY ORDER BY TOTAL_REVENUE_AT_RISK DESC"""

SQL_AT_RISK_KPI = """
SELECT COUNT(*) AS TOTAL_AT_RISK, ROUND(SUM(REVENUE_AT_RISK), 2) AS TOTAL_REVENUE_AT_RISK,
    ROUND(AVG(CHURN_PROBABILITY), 3) AS AVG_CHURN_PROB,
    ROUND(AVG(DAYS_SINCE_CONTACT), 0) AS AVG_DAYS_SINCE_CONTACT
FROM INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES"""

SQL_ACCEPTANCE_RATE = """
SELECT ROUND(AVG(CASE WHEN ACCEPTED THEN 1 ELSE 0 END) * 100, 1) AS ACCEPTANCE_RATE_PCT,
    ROUND(AVG(FEEDBACK_RATING), 2) AS AVG_RATING, COUNT(*) AS TOTAL_FEEDBACK
FROM INSURANCE_AI_HUB.ANALYTICS.RECOMMENDATION_FEEDBACK"""

SQL_ACCEPTANCE_BY_PRODUCT = """
SELECT pr.PRODUCT_NAME, pr.POLICY_TYPE, pr.PLAN_TIER,
    COUNT(f.FEEDBACK_ID) AS FEEDBACK_COUNT,
    ROUND(AVG(CASE WHEN f.ACCEPTED THEN 1 ELSE 0 END) * 100, 1) AS ACCEPTANCE_RATE,
    ROUND(AVG(f.FEEDBACK_RATING), 2) AS AVG_RATING,
    ROUND(AVG(r.MATCH_SCORE), 1) AS AVG_MATCH_SCORE
FROM INSURANCE_AI_HUB.ANALYTICS.RECOMMENDATIONS r
JOIN INSURANCE_AI_HUB.ANALYTICS.PRODUCTS pr ON r.PRODUCT_ID = pr.PRODUCT_ID
JOIN INSURANCE_AI_HUB.ANALYTICS.RECOMMENDATION_FEEDBACK f ON r.RECOMMENDATION_ID = f.RECOMMENDATION_ID
GROUP BY pr.PRODUCT_NAME, pr.POLICY_TYPE, pr.PLAN_TIER
HAVING COUNT(f.FEEDBACK_ID) >= 3 ORDER BY ACCEPTANCE_RATE DESC"""

SQL_SCORE_DISTRIBUTION = """
SELECT CASE
    WHEN MATCH_SCORE < 50 THEN '0-49' WHEN MATCH_SCORE < 60 THEN '50-59'
    WHEN MATCH_SCORE < 70 THEN '60-69' WHEN MATCH_SCORE < 80 THEN '70-79'
    WHEN MATCH_SCORE < 90 THEN '80-89' ELSE '90-100'
    END AS SCORE_RANGE, COUNT(*) AS REC_COUNT
FROM INSURANCE_AI_HUB.ANALYTICS.RECOMMENDATIONS GROUP BY SCORE_RANGE ORDER BY SCORE_RANGE"""

SQL_REC_BY_STATUS = """
SELECT STATUS, COUNT(*) AS CNT FROM INSURANCE_AI_HUB.ANALYTICS.RECOMMENDATIONS
GROUP BY STATUS ORDER BY CNT DESC"""

SQL_DQ_SCORES_TREND = """
SELECT TABLE_NAME, SCORE_DATE, OVERALL_SCORE, COMPLETENESS_SCORE, ACCURACY_SCORE, CONSISTENCY_SCORE,
    RULES_PASSED, RULES_FAILED, TREND
FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES ORDER BY TABLE_NAME, SCORE_DATE"""

SQL_DQ_FAILED_RULES = """
SELECT r.RULE_NAME, r.TARGET_TABLE, r.TARGET_COLUMN, r.SEVERITY, r.IS_CRITICAL,
    res.PASS_RATE, res.FAILED_RECORDS, res.TOTAL_RECORDS, res.EXECUTION_DATE
FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_RULES r
JOIN INSURANCE_AI_HUB.DATA_QUALITY.DQ_RESULTS res ON r.RULE_ID = res.RULE_ID
WHERE res.STATUS = 'FAIL' ORDER BY r.SEVERITY, res.PASS_RATE ASC"""

SQL_COLUMN_HEALTH = """
SELECT TABLE_NAME, COLUMN_NAME, HEALTH_STATUS, IS_CRITICAL,
    ROUND(NULL_PCT, 1) AS NULL_PCT, ROUND(DUPLICATE_PCT, 1) AS DUPLICATE_PCT,
    OUTLIER_COUNT, ROUND(SCORE, 1) AS HEALTH_SCORE
FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_COLUMN_HEALTH ORDER BY SCORE ASC"""

SQL_DQ_KPI = """
SELECT ROUND(AVG(OVERALL_SCORE), 1) AS AVG_SCORE,
    SUM(RULES_FAILED) AS TOTAL_FAILURES, SUM(RULES_PASSED) AS TOTAL_PASSED
FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES
WHERE SCORE_DATE = (SELECT MAX(SCORE_DATE) FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES)"""

# ═══════════════════════════════════════
# HOME PAGE — cross-domain executive queries
# ═══════════════════════════════════════

SQL_HOME_ACTIVE_POLICIES = """
SELECT COUNT(*) AS ACTIVE_POLICIES,
    COUNT(DISTINCT POLICY_TYPE) AS POLICY_TYPES,
    ROUND(SUM(PREMIUM_AMOUNT), 2) AS TOTAL_PREMIUM_BOOK
FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES
WHERE POLICY_STATUS = 'Active'"""

SQL_HOME_HIGH_RISK_SEGMENTS = """
SELECT p.POLICY_TYPE, p.PLAN_TIER,
    ROUND(AVG(p.LOSS_RATIO), 3) AS AVG_LOSS_RATIO,
    COUNT(*) AS POLICY_COUNT,
    ROUND(SUM(p.PREMIUM_AMOUNT), 2) AS PREMIUM_EXPOSURE
FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES p
WHERE p.POLICY_STATUS = 'Active' AND p.LOSS_RATIO > 0.7
GROUP BY p.POLICY_TYPE, p.PLAN_TIER
ORDER BY AVG_LOSS_RATIO DESC
LIMIT 5"""

SQL_HOME_CRITICAL_DQ_ISSUES = """
SELECT r.RULE_NAME, r.TARGET_TABLE, r.SEVERITY,
    res.PASS_RATE, res.FAILED_RECORDS
FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_RULES r
JOIN INSURANCE_AI_HUB.DATA_QUALITY.DQ_RESULTS res ON r.RULE_ID = res.RULE_ID
WHERE res.STATUS = 'FAIL' AND r.IS_CRITICAL = TRUE
ORDER BY res.PASS_RATE ASC
LIMIT 5"""

SQL_HOME_TOP_AT_RISK = """
SELECT RISK_CATEGORY,
    COUNT(*) AS ACCOUNTS,
    ROUND(SUM(REVENUE_AT_RISK), 2) AS REVENUE_AT_RISK,
    ROUND(AVG(CHURN_PROBABILITY), 3) AS AVG_CHURN_PROB
FROM INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES
GROUP BY RISK_CATEGORY
ORDER BY REVENUE_AT_RISK DESC
LIMIT 4"""

SQL_HOME_REC_SUMMARY = """
SELECT COUNT(*) AS TOTAL_RECS,
    SUM(CASE WHEN STATUS = 'Accepted' THEN 1 ELSE 0 END) AS ACCEPTED,
    SUM(CASE WHEN STATUS = 'Pending' THEN 1 ELSE 0 END) AS PENDING,
    SUM(CASE WHEN STATUS = 'Rejected' THEN 1 ELSE 0 END) AS REJECTED
FROM INSURANCE_AI_HUB.ANALYTICS.RECOMMENDATIONS"""
