-- ============================================================
-- INSURANCE AI HUB - RBAC Grants
-- Roles, role hierarchy, and privilege grants
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- -------------------------------------------------------
-- 1. Create roles
-- -------------------------------------------------------
CREATE ROLE IF NOT EXISTS INSURANCE_ANALYTICS_READER;
CREATE ROLE IF NOT EXISTS INSURANCE_DOCUMENTS_READER;
CREATE ROLE IF NOT EXISTS INSURANCE_DQ_STEWARD;
CREATE ROLE IF NOT EXISTS INSURANCE_HUB_USER;

-- -------------------------------------------------------
-- 2. Role hierarchy: INSURANCE_HUB_USER inherits all 3
-- -------------------------------------------------------
GRANT ROLE INSURANCE_ANALYTICS_READER TO ROLE INSURANCE_HUB_USER;
GRANT ROLE INSURANCE_DOCUMENTS_READER TO ROLE INSURANCE_HUB_USER;
GRANT ROLE INSURANCE_DQ_STEWARD       TO ROLE INSURANCE_HUB_USER;

-- -------------------------------------------------------
-- 3. INSURANCE_ANALYTICS_READER grants
-- -------------------------------------------------------
GRANT USAGE ON DATABASE INSURANCE_AI_HUB TO ROLE INSURANCE_ANALYTICS_READER;
GRANT USAGE ON SCHEMA INSURANCE_AI_HUB.ANALYTICS TO ROLE INSURANCE_ANALYTICS_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURANCE_AI_HUB.ANALYTICS TO ROLE INSURANCE_ANALYTICS_READER;

-- -------------------------------------------------------
-- 4. INSURANCE_DOCUMENTS_READER grants
-- -------------------------------------------------------
GRANT USAGE ON DATABASE INSURANCE_AI_HUB TO ROLE INSURANCE_DOCUMENTS_READER;
GRANT USAGE ON SCHEMA INSURANCE_AI_HUB.DOCUMENTS TO ROLE INSURANCE_DOCUMENTS_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURANCE_AI_HUB.DOCUMENTS TO ROLE INSURANCE_DOCUMENTS_READER;

-- -------------------------------------------------------
-- 5. INSURANCE_DQ_STEWARD grants
-- -------------------------------------------------------
GRANT USAGE ON DATABASE INSURANCE_AI_HUB TO ROLE INSURANCE_DQ_STEWARD;
GRANT USAGE ON SCHEMA INSURANCE_AI_HUB.DATA_QUALITY TO ROLE INSURANCE_DQ_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURANCE_AI_HUB.DATA_QUALITY TO ROLE INSURANCE_DQ_STEWARD;

-- -------------------------------------------------------
-- 6. INSURANCE_HUB_USER additional grants
-- -------------------------------------------------------
GRANT USAGE ON WAREHOUSE INSURANCE_AI_HUB_WH TO ROLE INSURANCE_HUB_USER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE INSURANCE_HUB_USER;

-- Cortex Agent access
GRANT USAGE ON CORTEX_AGENT INSURANCE_AI_HUB.ANALYTICS.INSURANCE_HUB_ORCHESTRATOR TO ROLE INSURANCE_HUB_USER;
GRANT USAGE ON CORTEX_AGENT INSURANCE_AI_HUB.ANALYTICS.PRODUCT_MATCHING_AGENT     TO ROLE INSURANCE_HUB_USER;
GRANT USAGE ON CORTEX_AGENT INSURANCE_AI_HUB.ANALYTICS.PRICE_OPTIMIZATION_AGENT   TO ROLE INSURANCE_HUB_USER;
GRANT USAGE ON CORTEX_AGENT INSURANCE_AI_HUB.ANALYTICS.MARKET_INTELLIGENCE_AGENT  TO ROLE INSURANCE_HUB_USER;
GRANT USAGE ON CORTEX_AGENT INSURANCE_AI_HUB.ANALYTICS.DATA_QUALITY_AGENT         TO ROLE INSURANCE_HUB_USER;
